version: '2'

services:
  web:
    image: nginx:latest
    container_name: laravel7x_web
    ports:
      - "80:8000"
    command: nginx-debug -g 'daemon off;'
    working_dir: /opt
    links:
      - php
    networks:
      - develop
    volumes:
      - ./public:/opt/public
      - ./laravel.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - php
  db:
    image: postgres:12.6-alpine
    container_name: laravel7x_database
    restart: always
#    command: 'echo "host all all all $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf'
    ports:
      - "5432:5432"
    volumes:
      - laravel7x:/var/lib/postgresql/data
    networks:
      - develop
    environment:
#      POSTGRES_DB: 'laravel'
#      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - develop

  php:
    image: php:7.3.4-fpm
    container_name: laravel7x_php
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh install.sh
    environment:
      INSTALL_VENDOR: 'y'
      USER: "$USER"
    networks:
      - develop
    depends_on:
      - db
    links:
      - db
networks:
  develop:
    driver: bridge
volumes:
  laravel7x:




